# This file is automatically generated: 2025-04-22T23:40:49.628281+00:00
# URL: https://autozoneloadtest.cloud.looker.com

view: blend_test {
  derived_table: {
    sql: 
-- b=eyJxdWVyaWVzIjpbIlFmVXJEbUVwbEtCaXhTN29nMzZTblYiLCJRZlVyRG1FcGxLQml4UzdvZzM2U25WIl0sInF1ZXJ5X3V1aWRzIjpbInExIiwicTMiXSwiam9pbnMiOlt7InR5cGUiOiJpbm5lciIsImpvaW5zIjpbeyJmcm9tX3F1ZXJ5X2luZGV4IjotMSwiZnJvbV9maWVsZCI6IiIsInRvX2ZpZWxkIjoiIn1dfSx7InR5cGUiOiJpbm5lciIsImpvaW5zIjpbeyJmcm9tX3F1ZXJ5X2luZGV4IjowLCJmcm9tX2ZpZWxkIjoib3JkZXJfaXRlbXNfYmlnLmNyZWF0ZWRfZGF0ZSIsInRvX2ZpZWxkIjoib3JkZXJfaXRlbXNfYmlnLmNyZWF0ZWRfZGF0ZSJ9XX1dfQ==
WITH q1 AS (-- raw sql results do not include filled-in values for 'order_items_big.created_date'


SELECT
    (DATE("created_at")) AS "order_items_big.created_date"
FROM
    "order_items_big" AS "order_items_big"
WHERE "store_id" > -1
GROUP BY
    1),
q3 AS (-- raw sql results do not include filled-in values for 'order_items_big.created_date'


SELECT
    (DATE("created_at")) AS "order_items_big.created_date"
FROM
    "order_items_big" AS "order_items_big"
WHERE "store_id" > -1
GROUP BY
    1)
SELECT q1."order_items_big.created_date" AS "q1.order_items_big.created_date", q3."order_items_big.created_date" AS "q3.order_items_big.created_date" FROM q1
INNER JOIN q3 ON q1."order_items_big.created_date" = q3."order_items_big.created_date" ;;
  }
  dimension: q1.order_items_big_created_date {
    label: "Created Date"
    view_label: "Order Items Big - Order Items Big"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."q1.order_items_big.created_date" ;;
  }
        
  dimension: q3.order_items_big_created_date {
    label: "Created Date"
    view_label: "Order Items Big - Order Items Big"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."q3.order_items_big.created_date" ;;
  }
        
}
        
explore: blend_test {
  hidden: yes
  label: "Blend test" 
}
