# This file is automatically generated: 2025-04-24T04:35:05.351828+00:00
# URL: https://autozoneloadtest.cloud.looker.com

            access_grant: jkrvnhositowq {
                user_attribute: group_attribute_for_blend
                allowed_values: [bryan, UserGroup]
            }
        
view: blend_jkrvnhositowq {
  derived_table: {
    sql: 
-- b=eyJxdWVyaWVzIjpbInBMNzNmY1hmb1FCQ25lcEMxUklhdXMiLCJwTDczZmNYZm9RQkNuZXBDMVJJYXVzIl0sInF1ZXJ5X3V1aWRzIjpbInEzIiwicTEiXSwiam9pbnMiOlt7InR5cGUiOiJpbm5lciIsImpvaW5zIjpbeyJmcm9tX3F1ZXJ5X2luZGV4IjotMSwiZnJvbV9maWVsZCI6IiIsInRvX2ZpZWxkIjoiIn1dfSx7InR5cGUiOiJpbm5lciIsImpvaW5zIjpbeyJmcm9tX3F1ZXJ5X2luZGV4IjowLCJmcm9tX2ZpZWxkIjoib3JkZXJfaXRlbXNfYmlnLmNyZWF0ZWRfZGF0ZSIsInRvX2ZpZWxkIjoib3JkZXJfaXRlbXNfYmlnLmNyZWF0ZWRfZGF0ZSJ9XX1dfQ==
WITH q3 AS (-- raw sql results do not include filled-in values for 'order_items_big.created_date'


SELECT
    (DATE("created_at")) AS "order_items_big.created_date"
FROM
    "order_items_big" AS "order_items_big"
WHERE "store_id" > -1
GROUP BY
    1),
q1 AS (-- raw sql results do not include filled-in values for 'order_items_big.created_date'


SELECT
    (DATE("created_at")) AS "order_items_big.created_date"
FROM
    "order_items_big" AS "order_items_big"
WHERE "store_id" > -1
GROUP BY
    1)
SELECT q3."order_items_big.created_date" AS "q3.order_items_big.created_date", q1."order_items_big.created_date" AS "q1.order_items_big.created_date" FROM q3
INNER JOIN q1 ON q3."order_items_big.created_date" = q1."order_items_big.created_date" ;;
  }
  dimension: q3.order_items_big_created_date {
    label: "Created Date"
    view_label: "Order Items Big - q3"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."q3.order_items_big.created_date" ;;
  }
        
  dimension: q1.order_items_big_created_date {
    label: "Created Date"
    view_label: "Order Items Big - q1"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."q1.order_items_big.created_date" ;;
  }
        
}
        
explore: blend_jkrvnhositowq {
  hidden: yes
  label: "Blend jkrvnhositowq" 
  required_access_grants: [access_grant_jkrvnhositowq]
}
