# This file is automatically generated: 2025-04-28T18:48:10.189078+00:00
# URL: https://autozoneloadtest.cloud.looker.com/explore/adb_blend/blend_urwggpjmwumbd

access_grant: access_grant_urwggpjmwumbd {
    user_attribute: group_attribute_for_blend
    allowed_values: [bryan, UserGroup]
}
        
view: blend_urwggpjmwumbd {
  derived_table: {
    sql: 
-- b=eyJxdWVyaWVzIjpbIm5hcDZFWUFuMUNLZUFwcGR6NmpQMmoiLCJqeHpTQVpEeGxsa3NvT0RjQ1VZWTdXIl0sInF1ZXJ5X3V1aWRzIjpbInExIiwicTMiXSwiam9pbnMiOlt7InR5cGUiOiJpbm5lciIsImpvaW5zIjpbeyJmcm9tX3F1ZXJ5X2luZGV4IjotMSwiZnJvbV9maWVsZCI6IiIsInRvX2ZpZWxkIjoiIn1dfSx7InR5cGUiOiJpbm5lciIsImpvaW5zIjpbeyJmcm9tX3F1ZXJ5X2luZGV4IjowLCJmcm9tX2ZpZWxkIjoib3JkZXJfaXRlbXNfYmlnLnVzZXJfaWQiLCJ0b19maWVsZCI6Im9yZGVyX2l0ZW1zX2JpZy51c2VyX2lkIn1dfV19
WITH q1 AS (SELECT
    "user_id" AS "order_items_big.user_id",
    COUNT(*) AS "order_items_big.count"
FROM
    "order_items_big" AS "order_items_big"
WHERE "store_id" > -1
GROUP BY
    1),
q3 AS (SELECT
    "user_id" AS "order_items_big.user_id",
    COUNT(*) AS "order_items_big.count"
FROM
    "order_items_big" AS "order_items_big"
WHERE "status" = 'Returned' AND "store_id" > -1
GROUP BY
    1)
SELECT q1."order_items_big.count" AS "q1.order_items_big.count", q1."order_items_big.user_id" AS "q1.order_items_big.user_id", q3."order_items_big.user_id" AS "q3.order_items_big.user_id", q3."order_items_big.count" AS "q3.order_items_big.count" FROM q1
INNER JOIN q3 ON q1."order_items_big.user_id" = q3."order_items_big.user_id" ;;
  }
  dimension: q1.order_items_big_count {
    label: "Count"
    view_label: "Order Items Big - q1"
    group_label: ""
    description: ""
    type: number
    sql: ${TABLE}."q1.order_items_big.count" ;;
  }
        
  dimension: q1.order_items_big_user_id {
    label: "User ID"
    view_label: "Order Items Big - q1"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."q1.order_items_big.user_id" ;;
  }
        
  dimension: q3.order_items_big_user_id {
    label: "User ID"
    view_label: "Order Items Big - q3"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."q3.order_items_big.user_id" ;;
  }
        
  dimension: q3.order_items_big_count {
    label: "Count"
    view_label: "Order Items Big - q3"
    group_label: ""
    description: ""
    type: number
    sql: ${TABLE}."q3.order_items_big.count" ;;
  }
        
}
        
explore: blend_urwggpjmwumbd {
  hidden: yes
  label: "Blend urwggpjmwumbd" 
  required_access_grants: [access_grant_urwggpjmwumbd]
}
