# This file is automatically generated: 2025-09-16T21:40:04.052904+00:00
# URL: https://autozoneloadtest.cloud.looker.com/explore/test/blend_eprxwxlcodhex

view: blend_eprxwxlcodhex {
  derived_table: {
    sql: -- b=eyJxdWVyaWVzIjpbIklLVDI0RlRhamJTS0lqNTZxTGpUVHAiLCJJS1QyNEZUYWpiU0tJajU2cUxqVFRwIl0sInF1ZXJ5X3V1aWRzIjpbInExIiwicTMiXSwiam9pbnMiOlt7InR5cGUiOiJpbm5lciIsImpvaW5zIjpbeyJmcm9tX3F1ZXJ5X2luZGV4IjotMSwiZnJvbV9maWVsZCI6IiIsInRvX2ZpZWxkIjoiIn1dfSx7InR5cGUiOiJpbm5lciIsImpvaW5zIjpbeyJmcm9tX3F1ZXJ5X2luZGV4IjowLCJmcm9tX2ZpZWxkIjoib3JkZXJfaXRlbXNfYmlnLmNyZWF0ZWRfbW9udGgiLCJ0b19maWVsZCI6Im9yZGVyX2l0ZW1zX2JpZy5jcmVhdGVkX21vbnRoIn1dfV19
WITH
  q1 AS (
    -- raw sql results do not include filled-in values for 'order_items_big.created_month'
    SELECT
      (
        TO_CHAR(DATE_TRUNC('month', "created_at"), 'YYYY-MM')
      ) AS "order_items_big.created_month"
    FROM
      "order_items_big" AS "order_items_big"
    WHERE
      "store_id" > -1
      AND (
        1 = 1
        /* 27.0  */
      )
    GROUP BY
      (DATE_TRUNC('month', "created_at"))
  ),
  q3 AS (
    -- raw sql results do not include filled-in values for 'order_items_big.created_month'
    SELECT
      (
        TO_CHAR(DATE_TRUNC('month', "created_at"), 'YYYY-MM')
      ) AS "order_items_big.created_month"
    FROM
      "order_items_big" AS "order_items_big"
    WHERE
      "store_id" > -1
      AND (
        1 = 1
        /* 27.0  */
      )
    GROUP BY
      (DATE_TRUNC('month', "created_at"))
  )
SELECT
  q1."order_items_big.created_month" AS "q1.order_items_big.created_month",
  q3."order_items_big.created_month" AS "q3.order_items_big.created_month"
FROM
  q1
  INNER JOIN q3
  ON q1."order_items_big.created_month" = q3."order_items_big.created_month" ;;
  }
  dimension: q1.order_items_big_created_month {
    label: "Created Month"
    view_label: "Order Items Big - q1"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."q1.order_items_big.created_month" ;;
  }
        
  dimension: q3.order_items_big_created_month {
    label: "Created Month"
    view_label: "Order Items Big - q3"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."q3.order_items_big.created_month" ;;
  }
        
}
        
explore: blend_eprxwxlcodhex {
  hidden: yes
  label: "Blend eprxwxlcodhex" 
}
