# This file is automatically generated: 2025-11-19T14:42:32.525103+00:00
# URL: https://autozoneloadtest.cloud.looker.com/explore/test/blend_hmkjcyozeysag

view: blend_hmkjcyozeysag {
  derived_table: {
    sql: WITH
  top_5 AS (
    SELECT
      select_one.one AS "select_one.one",
      select_two.two AS "select_two.two",
      COUNT(DISTINCT select_two.two) AS "select_two.count"
    FROM
      LOOKER_SCRATCH.ZK_snowflake_test_select_one AS select_one
      CROSS JOIN LOOKER_SCRATCH.ZK_snowflake_test_select_two AS select_two
    GROUP BY
      1,
      2
  ),
  q3 AS (
    SELECT
      select_one.one AS "select_one.one",
      select_two.two AS "select_two.two",
      COUNT(DISTINCT select_two.two) AS "select_two.count"
    FROM
      LOOKER_SCRATCH.ZK_snowflake_test_select_one AS select_one
      CROSS JOIN LOOKER_SCRATCH.ZK_snowflake_test_select_two AS select_two
    GROUP BY
      1,
      2
  )
SELECT
  top_5."select_one.one" AS "top_5.select_one.one",
  top_5."select_two.two" AS "top_5.select_two.two",
  top_5."select_two.count" AS "top_5.select_two.count",
  q3."select_one.one" AS "q3.select_one.one",
  q3."select_two.two" AS "q3.select_two.two",
  q3."select_two.count" AS "q3.select_two.count"
FROM
  top_5
  LEFT JOIN q3
  ON top_5."select_one.one" = q3."select_one.one" ;;
  }
  dimension: top_5.select_one_one {
    label: "One"
    view_label: "Top 5"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."top_5.select_one.one" ;;
  }
        
  dimension: top_5.select_two_two {
    label: "Two"
    view_label: "Top 5"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."top_5.select_two.two" ;;
  }
        
  dimension: top_5.select_two_count {
    label: "Count"
    view_label: "Top 5"
    group_label: ""
    description: ""
    type: number
    sql: ${TABLE}."top_5.select_two.count" ;;
  }
        
  dimension: q3.select_one_one {
    label: "One"
    view_label: "Select One (Copy)"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."q3.select_one.one" ;;
  }
        
  dimension: q3.select_two_two {
    label: "Two"
    view_label: "Select One (Copy)"
    group_label: ""
    description: ""
    type: string
    sql: ${TABLE}."q3.select_two.two" ;;
  }
        
  dimension: q3.select_two_count {
    label: "Count"
    view_label: "Select One (Copy)"
    group_label: ""
    description: ""
    type: number
    sql: ${TABLE}."q3.select_two.count" ;;
  }
        
}
        
explore: blend_hmkjcyozeysag {
  hidden: yes
  label: "Blend hmkjcyozeysag" 
}
